
http://blog.csdn.net/thefutureisour/article/details/7599537 隐藏console窗口
http://blog.sina.com.cn/s/blog_6bbd2dd101012dbh.html 显示汉字
http://blog.csdn.net/qianqing13579/article/details/45318279 mat中的属性
http://bbs.chinaunix.net/thread-3588524-1-1.html c++ 宏循环


http://blog.csdn.net/scyscyao/article/details/5987581 模式识别


http://www.cnblogs.com/easymind223/archive/2013/02/14/2911170.html stroke filter

http://blog.csdn.net/lanbing510/article/details/40585789 如何解决vector 析构异常 opencv Assert _CrtIsValidHeapPointer


tesseract source

** SetPageSegMode
void TessBaseAPI::SetPageSegMode(PageSegMode mode) {
  if (tesseract_ == NULL)
    tesseract_ = new Tesseract;
  tesseract_->tessedit_pageseg_mode.set_value(mode);
}



* modi
http://wenku.baidu.com/link?url=tvvByFZ_TTMCDkQ_XoEwmXAwezKP7h6lDiM0O0bPFzdnS0Kobn3-UC-ZMqCLWZ4AEfjPoLkD0fbPAeOzQm3AA6hhzGEdSO6ihIOT9pw3L43 vb modi sample
http://www.codeproject.com/Articles/17291/OCR-With-MODI-in-Visual-C vc modi sample
https://github.com/MathiasPius/modil write and read bpp image and ocr
http://zhidao.baidu.com/link?url=8aHlunjqiUKC5Sz17U91FpkPm_1K5G2oy486lE_o6hAUDvFL3PW-esKPsnjDcoSeNmi9mw7Bddr0pWT3JII7ga dll name
http://www.jb51.net/dll/interop.modi.dll.html#download dll download




* training
** url
http://blog.csdn.net/dragoo1/article/details/8439373 most clear, but missing
http://wenku.baidu.com/link?url=qdk8BL-ZRMdvleCjks90WkaZCi4orgOKQeysyC59llHR0bsqg04uOKYg761vHyT-iIdmCSKrzVzCOJP68DrDOMmkP4WJiwnqJ_HGiOGA3gC font file
http://www.cnblogs.com/huyulin/p/3305563.html one error for shape

** step
create box file via tif
create font_properties with line "song 0 0 0 0 0"

..\tesseract test.song.exp01.tif test.song.exp01 nobatch box.train
..\tesseract test.song.exp02.tif test.song.exp02 nobatch box.train
..\unicharset_extractor test.song.exp01.box test.song.exp02.box
..\mftraining -U unicharset -O test.unicharset test.song.exp01.tr test.song.exp02.tr
..\cntraining test.song.exp01.tr test.song.exp02.tr
rename normproto test.normproto
rename Microfeat test.Microfeat
rename inttemp test.inttemp
rename pffmtable test.pffmtable
rename shapetable test.shapetable
..\combine_tessdata test.




** font
http://www.bianceng.cn/Programming/cplus/201404/40531.htm by directwrite
http://blog.163.com/guo_linda/blog/static/1237730572011425105235527/ common use of cfontdialog
http://www.jizhuomi.com/software/175.html write font in dialog
useful http://stackoverflow.com/questions/11253827/too-many-fonts-when-enumerating-with-enumfontfamiliesex-function
and http://stackoverflow.com/questions/3486546/enumerating-active-fonts-in-c-sharp-using-dll-call-to-enumfontfamiliesex-has-me
sample http://bbs.csdn.net/topics/390461315

* GEB
http://www.zhihu.com/question/19554287

** download
http://vdisk.weibo.com/s/CdPPQHuuLi6pJ


* obs
start https://github.com/jp9000/obs-studio/wiki/Install-Instructions#windows
  http://blog.csdn.net/tanningzhong/article/details/51907039
  http://www.52codes.net/article/4849.html
  C1001 http://www.52codes.net/article/4996.html

* 世界观

物质，肉体是离散的
能量，精神是连续的
即物质世界与理想世界

能量的运动，即空间？
能量向物质的转化，即时间？
空间是连续的，时间是离散的？或者相反？

连续的能量，向离散的物质的降维过程，即宇宙

能量的有序组合，即信息
信息超过临界的聚积，即生命

物质有位置，能量有运动，即测不准原理

连续世界，即无边玄妙方广世界

不可判定，即自主意识？

存在与时间？

《地球之外的生命》 ：宇宙是一种精神

原子跃迁序列，与音乐的关系？

四种物理力：离散之间，连续之间，离散向连续，连续向离散

！！！科学就是放弃物理上的可解释性，而换取数学上的可描述性和可预测性！！！

！！！时间是直觉的一种形式！！！康德

** 康托尔集的十进制表示
将线段等分10份，标为0-9,去调1,3,5,7,9段。将剩余的0,2,4,6,8段，每段等分10份，并如此反复无穷。
得到的点集，是所有仅含数字0,2,4,6,8的实数。
边长 r=(1/2)^n
边数 N(r)＝5^n
D=lnN(r)/ln(1/r)=ln5/ln2


* xbrl
** step
http://wenku.baidu.com/link?url=Euc5xbzH-NnJ60LMH7FSgr52htOncJumDKYhmDpP90a8RumamRurGcMLxRPtThbW4mR3QvBuKk_9ytn75l0VokdByNIQJx6x-HRJkPHRuka
NXD:Apache的Xindice  now in http://attic.apache.org/  not used now !!

http://stackoverflow.com/questions/2336979/dump-a-java-hashmapk-v-to-xml-and-back
xstream

http://stackoverflow.com/questions/18830638/java-parse-xml-and-bind-all-data-content-to-a-map-k-v
java DOM

http://docs.oracle.com/cd/B10501_01/appdev.920/a96620/xdb04cre.htm
oracel xmltype

http://www.oschina.net/project/tag/263/xml-database
six type xml db

http://couchdb.apache.org/
doc database

http://www.codeproject.com/Articles/76814/WebControls/
http://www.codeproject.com/Articles/131675/Generate-SQL-Database-Schema-from-XML-Part-Code
create database table from XML

http://blog.csdn.net/sfrankzhang/article/details/8151170
FOR XML AUTO in SQL server

http://blog.csdn.net/gobitan/article/details/1545998
desc four native-xml database

http://www.oracle.com/technetwork/database/berkeleydb/overview/index-083851.html
http://blog.csdn.net/dongle2001/article/details/1565240 chinese version desc
Oracle Berkeley DB XML

** Berkeley DB
http://docs.oracle.com/cd/E17276_01/html/toc.htm classic
http://www.cnblogs.com/me115/p/3395396.html chinese data for insert query : faster than redis
http://www.cnblogs.com/me115/p/3324040.html normal c++
http://www.micmiu.com/nosql/berkeley/berkeley-tutorial/ normal java
http://blog.csdn.net/gobitan/article/details/1552101 shell

*** following classic
http://docs.oracle.com/cd/E17276_01/html/intro_xml/index.html

http://docs.oracle.com/cd/E17276_01/html/intro_xml/introduction.html
BDX支持以XQuery方式快速查询百万记的XML文件。BDX默认使用节点存储方式，以提高查询效率；此时如进行文件查询，返回同构的XML文档。


* daily
20160725 POC for bitmap and CDC, POC for EnumFontFamiliesEx
